<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOBiGaN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOBiGaN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDOBiGaN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDOBiGaN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDOBiGaN\App_KernelDevDebugContainer([
    'container.build_hash' => 'DOBiGaN',
    'container.build_id' => 'b3904f0c',
    'container.build_time' => 1608522913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOBiGaN');
