<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSOcqSjw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSOcqSjw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSOcqSjw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSOcqSjw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSOcqSjw\App_KernelDevDebugContainer([
    'container.build_hash' => 'SOcqSjw',
    'container.build_id' => 'fc3ab804',
    'container.build_time' => 1608155263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSOcqSjw');
